config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"

  resources :users
  resources :orders
  resources :menus

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  get "/home" => "menu_items#home", as: :new_menu_items_home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many :menu_items
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :menu
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :menu_item
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  has_secure_password
  has_many :orders

  def self.clerk
    all.where("role=?", "clerk")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user

    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to menus_path
    else
      render "index"
    end
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :ensure_user_logged_in

  def index
  end

  def create
    menu_item = MenuItem.create!(
      name: params[:name],
      description: params[:description],
      price: params[:price],
    )
    render plain: "Menu Item has been created succesfully"
  end

  def destroy
    menu_item_id = params[:id]
    menu_item = MenuItem.find(menu_item_id)
    menu_item.destroy
    redirect_to menus_path
  end

  def home
    render "home"
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :ensure_user_logged_in

  def index
    render "index"
  end

  def create
    new_menu = Menu.new(
      name: params[:name],
    )
    if new_menu.save
      redirect_to menus_path
    else
      flash[:error] = new_menu.errors.full_messages.join(", ")
      redirect_to menus_path
    end
  end

  def destroy
    id = params[:id]
    menu = Menu.all.find(id)
    menu.destroy
    redirect_to menus_path
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :ensure_user_logged_in

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user and user.authenticate(params[:password])
      flash[:success] = "Logged-in Succesfully"
      session[:current_user_id] = user.id
      redirect_to new_menu_items_home_path
    else
      flash[:error] = "Your Login attempt was invalid.Please Retry"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    render "index"
  end

  def create
    role = "customer"
    if session[:current_user_id]
      role = "clerk"
    end
    user = User.new(
      name: params[:name],
      email: params[:email],
      role: role,
      phone_number: params[:phone_number],
      address: params[:address],
      password: params[:password],
    )
    if user.save
      if session[:current_user_id]
        redirect_to users_path
      else
        session[:current_user_id] = user.id
        flash[:success] = "Signed-up Successfully!!"
        redirect_to new_menu_items_home_path
      end
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_sessions_path
    end
  end

  def new
    render "users/new"
  end

  def destroy
    id = params[:id]
    user = User.all.find(id)
    user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class="Home-title">Welcome to the Cafeteria Home-Page</p>

<h3 class="Home-authenticate">If you are a new user,<%= link_to "Sign-up here", new_user_path%></h3>
<h3 class="Home-authenticate">If you are an existing user, <%=link_to "Sign-in here",new_sessions_path%></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeteriaManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <% if @current_user.role == "owner" %>
        <div class="Navigation">
          <%= link_to "Home", new_menu_items_home_path%>
          <%= link_to "Orders", orders_path%>
          <%= link_to "Menus", menus_path%>
          <%= link_to "Users", users_path%>
        </div>
        <%= link_to "Sign-out", destroy_session_path,method: "delete" %>
      <% elsif @current_user.role == "clerk" %>
        <div class="Navigation">
          <%= link_to "Home", new_menu_items_home_path%>
          <%= link_to "Orders", orders_path%>
          <%= link_to "Menus", menus_path%>
        </div>
        <%= link_to "Sign-out", destroy_session_path,method: "delete" %>
      <% else %>
         <div class="Navigation">
          <%= link_to "Home", new_menu_items_home_path%>
         </div>
         <%= link_to "Sign-out", destroy_session_path,method: "delete" %>
      <% end %>
    <% end %>
    <% if flash[:error] %>
      <p class="Flash-error"> <%= flash[:error] %> </p>
    <% end %>
    <% if flash[:success] %>
      <p class="Flash-success"> <%= flash[:success] %> </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/menu_items/home.html.erb
 <h2>Welcome To Cafeteria Manager</h2>

app/views/menus/index.html.erb
<h1 class="Menus-title">Menus</h1>
<%= form_with(url: "/menus", method: "post", class: "Menus") do %>
  <p class="Menus-label">Add a Menu:</p>
    <%= text_field_tag 'name', '' , placeholder: "Add-Menu", class: 'Menus-name'
    %>
  <%= button_tag("Add-Menu",type: "submit",class: "Menus-button") %>
<% end %>
<h2>Menus-List</h2>
<ul>
    <% Menu.all.each do |menu| %>
        <li class="Menus-view">
          <div class="Menus-container">
            <%= form_with(url: "/menus/#{menu.id}" , method: "put") do %>
              <%= check_box_tag("",
                  value=nil,
                  {onclick: "this.form.submit()",
                  class: "Menus-checkbox"})
              %>
            <% end %>
            <p class="Menus-display"><%= menu.name %></p>
            <a class="Menu-delete ">
              <%= form_with(url: "/menus/#{menu.id}" , method: "delete") do %>
                <%= image_submit_tag("trash.svg") %>
              <% end %>
            </a>
          </div>
        </li>
   <% end %>
  </ul>

app/views/orders/index.html.erb
<h2>Orders</h2>

app/views/users/index.html.erb
 <div class="Navigation">
          <%= link_to "Home", new_menu_items_home_path%>
          <%= link_to "Orders", orders_path%>
          <%= link_to "Menus", menus_path%>
          <%= link_to "Users", users_path%>
        </div>
<h2>Users<h2>
<ul>
  <% User.clerk.each do |clerk| %>
    <li class="User">
      <div class="User-container">
        <p class = "User-name"><%=clerk.name%></p>
        <a class="User-delete ">
                <%= form_with(url: "/users/#{clerk.id}" , method: "delete") do %>
                  <%= image_submit_tag("trash.svg") %>
                <% end %>
        </a>
      </div>
    </li>
  <% end %>
</ul>
<div class="Users">
<h3>Add User:<%= link_to "Add-User", new_user_path%></h3>
</div>

app/views/users/new.html.erb
<p class="NewUsers-title">Welcome New user!</p>

<section class = "UsersNew">
  <%= form_with url: users_path do |form| %>
    <div class="Form-section">
      <p class="FormInput-label">Name:</p>
      <%= form.text_field :name, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Email:</p>
      <%= form.email_field :email, class: "Form-input"%>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Phone Number:</p>
      <%= form.telephone_field :phone_number, class: "Form-input"%>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Address:</p>
      <%= form.text_area :address, class: "Form-input"%>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Password:</p>
      <%= form.password_field :password, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <%= form.submit "Sign-up!", class: "Form-submit"%>
    </div>
  <% end %>
</section>